# Generated by Django 6.0.4 on 2026-04-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('cnic', models.CharField(max_length=15)),
                ('cell', models.CharField(max_length=15)),
                ('job_title_working', models.CharField(max_length=200)),
                ('for_job', models.CharField(max_length=200)),
                ('skill_set', models.TextField()),
                ('department', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField()),
            ],
        ),
    ]
